name       : libldm
version    : 0.2.4
release    : 5
source     :
    - https://github.com/mdbooth/libldm/archive/libldm-0.2.4.tar.gz : 9c941b40655ade5c3ab7da9d1b957df9400d88a59af090c87d1aa9971b0df84c
license    :
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  : system.utils
summary    : Tool for managing Microsoft Windows dynamic disks
description: |
    Tool for managing Microsoft Windows dynamic disks
builddeps  :
    - pkgconfig(devmapper)
    - pkgconfig(json-glib-1.0)
    - gtk-doc
setup      : |
    %patch -p1 < $pkgfiles/0001-Remove-deprecated-g_type_class_add_private.patch
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
