name       : libldm
version    : 0.2.3
release    : 3
source     :
    - https://github.com/mdbooth/libldm/archive/libldm-0.2.3.tar.gz : bc2d930f46f070d446e587f65f66b2fca4af5017439f6f821ae45bff7cb944ad
license    :
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  : system.utils
summary    : Tool for managing Microsoft Windows dynamic disks
description: |
    Tool for managing Microsoft Windows dynamic disks
builddeps  :
    - pkgconfig(devmapper)
    - pkgconfig(json-glib-1.0)
    - gtk-doc
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
