name       : libldm
version    : 0.2.5
release    : 10
source     :
    - https://github.com/mdbooth/libldm/archive/refs/tags/libldm-0.2.5.tar.gz : 61bb2f2367b1df59f818cb96794d1770a0def956bd2c343dccf1425dae3021b5
license    :
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  : system.utils
summary    : Tool for managing Microsoft Windows dynamic disks
description: |
    Tool for managing Microsoft Windows dynamic disks
builddeps  :
    - pkgconfig(devmapper)
    - pkgconfig(json-glib-1.0)
    - gtk-doc
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
